### ISSUE TITLE
How to reverse the "clang server" vscode installation

### ISSUE THREAD

**Issue by uuc110** [HolyBlackCat/cpp-tutorials#1]
Sorry!! I went ahead and clicked the Install server. was manually installing important. since I installed the suggested server and then manually? how Do I revert it? 

```
NOTE: If Clangd suggests downloading a "language server", refuse. It's not useful since we already installed the same thing from MSYS2. ([Why not the official Clang installer?](https://github.com/HolyBlackCat/cpp-tutorials/blob/master/why_not_official_clang_installer.md) applies to this as well.)
```

Issue 2:

This opens on pressing F5 and doesn't close and debugging stops. and in it is written ad `-g`. do I have to add `-g` in task.json in the label Compile something like this
![image](https://github.com/user-attachments/assets/f0d7cf91-8c43-4af4-82e6-e6ebdb530035)

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile",
            "type": "shell",
            "command": "clang++ ${fileBasename} -o ${fileBasenameNoExtension} -g",
            "problemMatcher": []
        },
        {
            "label": "Run",
            "type": "shell",
            "command": "./${fileBasenameNoExtension}",
            "problemMatcher": [],
            "dependsOn": "Compile",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

```

**Comment by HolyBlackCat** [comment]
(1) - Yeah, the language server it downloads by default is no good, because it operates in MSVC-compatible mode by default (wants to have a VS installation instead of using MinGW). You can revert this by removing `"clangd.path"` from `settings.json` (or from the GUI: go to the settings, search for `clangd path` (it will be set to `C:\Users\Username\AppData\...`), click the 'gear' icon to the left of it, press `Reset`). I'll add this to the tutorial as well.

(2) - It's hard to tell with limited information, but it looks to me like the debugging has started, and paused on a breakpoint (did you place a breakpoint?). Check the debug tab at the left, and the debug console. You can ask for help with this in [C++ discord](https://discord.com/invite/tccpp) (`@` me there, I'll help if I'm online).

**Comment by uuc110** [comment]
I have changed the Clangd path to my msys2 path which you mentioned to download for the server.

Well, it worked. didn't knew what was wrong but worked😂
